[google_sheets]
type = "service_account"
project_id = "auto-beauty-rewards"
private_key_id = "565b20a521e3fe929746ad01da8b775f91ae400d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCYhmJkEqKmWuBn
Lz2DO8E10ggD3a+1gRwnt6tTjhcx7yERDvNIR6T4qI14946CLyQOgrhAWYuO4Ar3
66gTNdkN6CjgTLwsS6FhN8k/ByEeMisHrPFbXaWrCrdZn7c39mg0FGaHb0bE5Qqm
xtgCVwEmL8kqP72xygUJUbELvVDFy5yBEcKC9uRAtUhXQ0MHhB4Aoh0yRtYnedpv
YRLBf4hzM07C3ejztXAOOhlgw780vocpJxSsDt8Y5P9bfys0WHDL/bW07uGtiGGl
nmZguIEpXOYTY7FV+tOiFuOVvekFvdgwId0TgCu12LToTJmH7oLmuAjaf1ObePXB
RG2eTAhXAgMBAAECggEANnjL+9xx7UKIYSGMcOlu09daWHMcVRCyqvab/9+/pew2
nX5+4UIBB3M+70ROR20pjesefZDdWB3onOkzIgU5qw9ORejxzUoHbQ58138m0z9s
gbXAjvZPe9n8aEwzpY9hYLQmd9kEZ747AxwBujgzZ11qlSWljDDPgqgDuGMYzUKg
zouWCcEVMNsdYkY6zJFCi7zjK89ZOCHwtezjrK7vjnxFIj9ygAwPmsQlNNWfQTc3
BdRSEpY/VpeMaRoBTxZlgAC/cjtbPixR0PBaXIwnosSncR+Oq8aXqwY6aoVfo9Dr
40Pwl2Mu5cgGV2ltZtEoTlyI4HKtePEFNVPtGtQJCQKBgQDIaxh2ZBrmiBZDgXMu
1MmZ48Q5ttRolqjUc1Sz4DpEYfASd3DkeMuOnuSLpn02nAe7q+1fQfnV+0PZ34Zk
ToAzUTtQ2gAKxT8vCH5uDcHP5DQikDsQalrrO015wyL4jJnAhzr7QG6VqBfbKJ0q
82jn+IJK3O7jTg8W+IEM21M9aQKBgQDC0ww9iBJ/zX9pfVv0HtJN2fIeYm624AqP
9VkTLhbv4xYDQT33ebLoFNVxGqo9YWRZoNWhdEtdDXnTYo8nTQLoInDkm0oK/ezf
oJtN+NfV4nXrtHnySXuXEt6B1sOJt8TeENgCMNQJguxXtPVBEO5U1MrtrFMYlN/b
pC5QzQWfvwKBgFRQkcsE1DhV2h/uLrnt9R5TrvKk0vlpIH+4QVMnKvwnw6rRKuJD
W0eV2wpRMW4u+CXg74zaobN+8I2RNuWuDMsKCo06GThuwOUVirLcAMRn+fLsgJyo
UbWSjkaCbIzqAaj4ezzGX3+AZwDhNjWij2i/qHi8N5fS+BAu3YO+JWe5AoGAMc+r
7X+A21Q7I0l93SiUNHtowAQCspcNnEjqgVDjZGn3EtX3dfKTn2rUN5rNs+vWsGPC
uwj0y9HKOBWW7EFwYNGNc6WQhMbvbS2vB3x8Ep9X7u+xzhSjmLimUyQJ0og9uVkt
IUJCtDvZGYOWwRAHH4FYcPQCOuK1aX7MqLQCoBkCgYBBLfRoBT2qPAbUWmvunl7x
V23Hx1b3DblTcTgr5GQ9RhMljQgz4pOOKtMy5Zd+DUyi4OGYrhpppEpb3ueMmnGQ
thrrIN7NBG6AvoxyBzW57Y2q5gjmvu+EwIM3tghOrFmlrGO9O89TV7BYvhxTKv6U
vkIg591+A24rV2cHanPVig==
-----END PRIVATE KEY-----"""
client_email = "voucher-sync-bot@auto-beauty-rewards.iam.gserviceaccount.com"
client_id = "115157767941262818674"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/voucher-sync-bot@auto-beauty-rewards.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
EMAIL_PASSWORD = "ABCkc3020?"
